language: r
cache: packages

r:
  - release
  - oldrel
  - devel

sudo: false

addons:
  apt:
    packages:
      - qpdf
      - libnlopt-dev

r_packages:
  - ade4
  - cclust
  - bipartite
  - labdsv
  - car
  - ellipse
  - coda
  - maptools
  - ape
  - picante

before_install:
  - tlmgr install sidecap

warnings_are_errors: false

r_build_args: " --compact-vignettes=gs+qpdf"

notifications:
  email:
    on_success: change
    on_failure: always

